### ISSUE TITLE
Readme ?

### ISSUE THREAD

**Issue by praetp** [Chrispresso/SnakeAI#1]
Maybe provide a Readme with dependencies and a short example ?
Thanks. Really enjoyed the movie.

**Comment by iamareebjamal** [comment]
And requirements.txt

**Comment by Chrispresso** [comment]
Alright, just added a `README.md` which talks about dependencies and getting the code up and running.  Let me know if it doesn't makes sense!

**Comment by Chrispresso** [comment]
Basic README and requirements.txt are now up.
