### ISSUE TITLE
I can not run this code

### ISSUE THREAD

**Issue by khazaee** [Chrispresso/SnakeAI#10]
I know I'm asking a ridiculous question, I have a lot of information about programming, but when I saw your video, I did not slow down and went to download it and tried to run it in vscode and run snake _app. Unfortunately, Chenta gave an error that I do not know exactly what to do to get the file running. I am copying the errors here and thank you very much for your help so that I can try this technology too. Although I know my problem is very simple and due to lack of my own information I can not execute the code.

Traceback (most recent call last):
  File "c:\Users\***\Desktop\Python\SnakeAI-master\snake_app.py", line 716, in <module>
    window = MainWindow(settings)
  File "c:\Users\***\Desktop\Python\SnakeAI-master\snake_app.py", line 90, in __init__
    self.timer.start(1000./fps)
TypeError: arguments did not match any overloaded call:
  start(self, int): argument 1 has unexpected type 'float'
  start(self): too many arguments

**Comment by quivXe** [comment]
Same

**Comment by michils** [comment]
I think your Argument for "Self" is wrong.
You should use "1000" instead of "1000."
The dot behind the 1000 makes the type to float. This could be the error. Please give a short feedback if this helps.
