### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by MaxLap** [Chrispresso/SnakeAI#4]
Hey, this is nice!
I'd love to play with it and possibly use code related to the genetic algorithm in my own projects. However, you do not have any software license on your project, which means that while yes, I can read the code, any using, modifying, distributing is basically prohibited. 

Of course, many people just assume that things are OK, that you basically just forgot, and that they can use it since its available. (And really, you are most likely not going to be suying anyway)

You can read more about not having a license here: https://choosealicense.com/no-permission/

And if you basically don't care that people use your software however they want, the MIT license is probably the easiest one to add:
https://choosealicense.com/licenses/mit/#suggest-this-license
You just need to add a LICENSE.txt to the root of the project with a copy pasted text (replacing the name and date)

**Comment by Chrispresso** [comment]
Added.
