### ISSUE TITLE
Snake AI not learning fast enough/not learning at all

### ISSUE THREAD

**Issue by megargayu** [Chrispresso/SnakeAI#9]
Hi @Chrispresso (and others)!

So today, I was testing out your Snake AI program. Everything is working fine (except that I added two lines of code for high DPI settings and I added a checkbox to the GUI and an FPS counter [the checkbox disables updating the snake and the brain, making it about 50x faster - for example, before, it was ~ 15 fps, and after, it was ~ 800 fps & the fps counter counts each move for an individual, not each individual]):
<details>
<summary>code</summary>

Changes made to `snake_app.py`
```python

# ... imports ...

SQUARE_SIZE = (35, 35)
QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)

class MainWindow(QtWidgets.QMainWindow):
    # ... code ...
    def init_window(self):
        # ... code ...
        self.fps_counter = QtWidgets.QLabel(self)
        self.fps_counter.setText("FPS: 0")
        self.fps_counter.setFont(QtGui.QFont("Georgia", 15, QtGui.QFont.Normal))
        self.fps_counter.setAlignment(QtCore.Qt.AlignRight)
        self.fps_counter.setGeometry(1160, 640, 100, 30)

        self.to_update = QtWidgets.QCheckBox("Update GUI elements", self)
        self.to_update.setChecked(True)
        self.to_update.setGeometry(1030, 640, 150, 30)
        self.to_update.clicked.connect(self.reset_fps) # Reset fps b/c fps is avg. and changing gui updating changes fps greatly

        self.last_update = time.time()
        self.sum_fps = 0
        self.updates = 0

    def reset_fps(self):
        self.sum_fps = 0
        self.updates = 0

    def update(self) -> None:
        if self.to_update.isChecked():
            self.snake_widget_window.update()
            self.nn_viz_window.update()

        if self.snake.is_alive:
            # ... code ...

        if time.time() - self.last_update == 0:
            time.sleep(0.0001)
        self.sum_fps += round(1 / (time.time() - self.last_update))
        self.updates += 1
        self.fps_counter.setText("FPS: %s" % round(self.sum_fps / self.updates))
        self.last_update = time.time()
    # ... end of changes ...
```
</details>

... but I don't think that has anything to do with the actual AI - please tell me if you want the full code, though)

Anyways, I was comparing how the snake was training on my computer compared to [your video](https://www.youtube.com/watch?v=vhiO4WsHA6c), and it's stuck on 3 apples! Even on generation _450_, the best score is 3. I hoped you could tell me how to fix this problem! All my settings in `settings.py` are exactly the way they were (except in the video, the vision is `distance` instead of `binary`, so I changed that). Here's a few pretty little `GIFs` using `ffmpeg`:

With `distance` vision:

![Snake AI Github](https://user-images.githubusercontent.com/56703197/89075446-0c37d580-d333-11ea-9f6c-b245b77bfbf0.gif)

With `binary` vision:

![Snake AI Github (binary)](https://user-images.githubusercontent.com/56703197/89080362-7786a500-d33d-11ea-8219-a4436ecbbd0a.gif)

Thanks in advance!
~ Ayush

**Comment by Chrispresso** [comment]
Hi @Programmer103 

From what I can gather, you're trying to update the paint only when the checkbox is marked. I designed this code probably in a less user friendly than I should have. When you disable `self.snake_widget_window.update()`, you are also disabling how the network performs the feed forward calculation to determine which direction to go. I can try to add some command line parameters to make it run without visualization, like I have in Mario.

Can you try going to `snake_app.py` and adjust the code under
```python
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow(settings)
    sys.exit(app.exec_())
```

to:
```python
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow(settings, show=False, fps=1000) 
    sys.exit(app.exec_())
```
This disables the initial showing and sets the update to be faster.
If you have the default printing stuff still in there, you should see after each generation some information be displayed about the best performing individual.

Also, did you run it before making your changes and did it work then?

**Comment by megargayu** [comment]
@Chrispresso 
I completely forgot that you put game logic in the Panels as well... Yes, it does work once I remove my code :P
